// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package channel

import (
	"demogogo/app/http/api/channel"
)

type ControllerV1 struct{}

func NewV1() channel.IChannelV1 {
	return &ControllerV1{}
}
