
# CLI tool, only in development environment.
# https://goframe.org/pages/viewpage.action?pageId=3673173
gfcli:
  gen:
    dao:
      - link: "mysql:root:123456@tcp(mysql:3306)/oneapi"
        tables: "tokens,channels,abilities"
        path: "./internal"
        jsonCase: "Snake"