// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"demogogo/internal/dao/internal"
	"demogogo/internal/model/entity"
)

// internalAbilitiesDao is internal type for wrapping internal DAO implements.
type internalAbilitiesDao = *internal.AbilitiesDao

// abilitiesDao is the data access object for table abilities.
// You can define custom methods on it to extend its functionality as you wish.
type abilitiesDao struct {
	internalAbilitiesDao
}

var (
	// Abilities is globally public accessible object for table abilities operations.
	Abilities = abilitiesDao{
		internal.NewAbilitiesDao(),
	}
)

// Fill with you ideas below.

func (m *abilitiesDao) GetRecordByModel(ctx context.Context, model string) (e *entity.Abilities, err error) {
	err = m.Ctx(ctx).Where("`group`=? and model=?", "default", model).Scan(&e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
