// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"demogogo/internal/dao/internal"
)

// internalAiChannelDao is internal type for wrapping internal DAO implements.
type internalAiChannelDao = *internal.AiChannelDao

// aiChannelDao is the data access object for table ai_channel.
// You can define custom methods on it to extend its functionality as you wish.
type aiChannelDao struct {
	internalAiChannelDao
}

var (
	// AiChannel is globally public accessible object for table ai_channel operations.
	AiChannel = aiChannelDao{
		internal.NewAiChannelDao(),
	}
)

// Fill with you ideas below.
