// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"context"
	"demogogo/internal/dao/internal"
	"demogogo/internal/model/entity"
)

// internalTokensDao is internal type for wrapping internal DAO implements.
type internalTokensDao = *internal.TokensDao

// tokensDao is the data access object for table tokens.
// You can define custom methods on it to extend its functionality as you wish.
type tokensDao struct {
	internalTokensDao
}

var (
	// Tokens is globally public accessible object for table tokens operations.
	Tokens = tokensDao{
		internal.NewTokensDao(),
	}
)

// Fill with you ideas below.

func (m *tokensDao) GetRecordById(ctx context.Context, id int64) (e *entity.Tokens, err error) {
	err = m.Ctx(ctx).Where("id=?", id).Scan(&e)
	if err != nil {
		return nil, err
	}
	return e, nil
}

func (m *tokensDao) GetRecordByKey(ctx context.Context, key string) (e *entity.Tokens, err error) {
	err = m.Ctx(ctx).Where("`key`=?", key).Scan(&e)
	if err != nil {
		return nil, err
	}
	return e, nil
}
